function pde = ex_BMPFC_data(para)

epsilon = para.epsilon;
M1 = para.M1;
M2 = para.M2;

pde = struct('epsilon',para.epsilon, ...
             'M1',para.M1, ...
             'M2',para.M2, ...
             'B',para.B, ...
             'w0',para.w0, ...
             'S1',para.S1, ...
             'S2',para.S2, ...
             'a1',para.a1, ...
             'a2',para.a2, ...
             'a12',para.a12, ...
             'alpha',para.alpha, ...
             'beta',para.beta, ...
             'gamma12',para.gamma12, ...
             'gamma1',para.gamma1, ...
             'gamma2',para.gamma2, ...
             'eta',para.eta, ...
             'eta1',para.eta1, ...
             'eta2',para.eta2, ...
             'theta',para.theta, ...
             'theta1',para.theta1, ...
             'theta2',para.theta2, ...
             'init1',@init1, ...
             'init2',@init2, ...
             'init3',@init3, ...
             'init4',@init4, ...
             'exact1',@exact1, ...
             'exact2',@exact2, ...
             'exact3',@exact3, ...
             'exact4',@exact4, ...
             'rhs1',@rhs1, ...
             'rhs2',@rhs2, ...
             'rhs3',@rhs3, ...
             'HH1',@HH1, ...
             'HH2',@HH2, ...
             'name','accuracy');

    function z = init1(x,y)
        z = exact1(x,y,0);
    end
    function z = init2(x,y)
        z = exact2(x,y,0);
    end
    function z = init3(x,y)
        z = exact3(x,y,0);
    end
    function z = init4(x,y)
        z = exact4(x,y,0);
    end
function z = exact1(x,y,t)  
       z = cos(2.*pi.*x/32).*cos(2.*pi.*y/32).*cos(t);
end
function z = exact2(x,y,t)  
       z = cos(pi.*x/32).*cos(pi.*y/32).*cos(t);
end
function z = exact3(x,y,t)  
       z = sin(8.*pi.*x/128).*sin(8.*pi.*y/128).*cos(t);
end
function z = exact4(x,y,t)  
       z = cos(8.*pi.*x/128).*cos(8.*pi.*y/128).*cos(t);
end
function z = HH1(x,y)  
       z = sin(8.*pi.*x/128).*cos(8.*pi.*y/256);
end
function z = HH2(y)  
       z = cos(8.*pi.*y/256);
end

end